service: notes-api

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  deploymentBucket:
    name: serverless-framework-deployments-us-east-1-6ab05a25-54a0
  environment:
    NOTES_TABLE: notes-api-dev-notes
    IMAGES_BUCKET: notes-api-images-123
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:us-east-1:*:table/notes-api-dev-notes"
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
          Resource: "arn:aws:s3:::notes-api-images-123/*"

functions:
  createNote:
    handler: src/handlers/createNote.handler
    events:
      - http:
          path: notes
          method: post
          cors: true

  getNotes:
    handler: src/handlers/getNotes.handler
    events:
      - http:
          path: notes
          method: get
          cors: true

  getNote:
    handler: src/handlers/getNote.handler
    events:
      - http:
          path: notes/{id}
          method: get
          cors: true

  updateNote:
    handler: src/handlers/updateNote.handler
    events:
      - http:
          path: notes/{id}
          method: put
          cors: true

  deleteNote:
    handler: src/handlers/deleteNote.handler
    events:
      - http:
          path: notes/{id}
          method: delete
          cors: true

  getUploadUrl:
    handler: src/handlers/uploadImage.getUploadUrl
    events:
      - http:
          path: notes/upload-url
          method: post
          cors: true

  saveImageUrl:
    handler: src/handlers/uploadImage.saveImageUrl
    events:
      - http:
          path: notes/save-image
          method: post
          cors: true

  deleteImage:
    handler: src/handlers/uploadImage.deleteImage
    events:
      - http:
          path: notes/{id}/image
          method: delete
          cors: true

resources:
  Resources:
    NotesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: notes-api-dev-notes
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST